name: auto-pull
on:
  push:
    branches:
      - action
  pull_request:
    branches:
      - action
  schedule:
    - cron: '0 0 * * 1'

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: get latest stable to main
        run: |
          git fetch --all
          git checkout action
          git push origin action:main -f
          git switch main
          git clone https://github.com/miniflux/v2.git; cd v2
          git checkout $(git describe --tags --abbrev=0)
          rm -rf .git README.md; mv * ..; cd ..; rm -rf v2
      - name: push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'auto pull'
          git push -f origin main
